### ISSUE TITLE
Define "copy-to-clipboard" interactions

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#1]
We've discussed the export to clipboard feature.
- Each piece page should have a button for export that will copy the piece's markdown to clipboard
- It will use a new API that mirrors the way that we fetch data as the bake sale
- From publishing point of view, we need to simultaneously publish signed markdown content for all the pieces. We'll need to do some thinking about how presentation information (that might be currently present in the HTML) is preserved in the markdown export
 - We need to have a way of viewing/copying/verifying signatures

Assigning @benhylau to define this feature in detail

**Comment by YurkoWasHere** [comment]
Function to copy text to clipboard. Works with modern browsers and legacy method as well.

```
//Copy to clipboard
function copyTextToClipboard(text) {    
    if (!navigator.clipboard) {
        fallbackCopyTextToClipboard(text);
        return;
    }
    navigator.clipboard.writeText(text).then(function () {
        console.log('Async: Copying to clipboard was successful!');
    }, function (err) {
        console.error('Async: Could not copy text: ', err);
    });
}
function fallbackCopyTextToClipboard(text) {
    var textArea = document.createElement("textarea");
    textArea.value = text;

    // Avoid scrolling to bottom
    textArea.style.top = "0";
    textArea.style.left = "0";
    textArea.style.position = "fixed";

    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
        var successful = document.execCommand('copy');
        var msg = successful ? 'successful' : 'unsuccessful';
        console.log('Fallback: Copying text command was ' + msg);
    } catch (err) {
        console.error('Fallback: Oops, unable to copy', err);
    }

    document.body.removeChild(textArea);
}
```

**Comment by uditvira** [comment]
@benhylau is working on this currently. We understand this feature as a "nice to have" feature and won't block the release of issue 02

**Comment by s-kennedy** [comment]
I merged PR #24 with my changes, just styling the copy button. We still need to add all the markdown files though.

**Comment by uditvira** [comment]
Just confirming @benhylau does the fetch markdown work across the different protocols (hyper/ipfs)?

**Comment by uditvira** [comment]
@s-kennedy has suggested:
- add a sentence or two explaining what it's for + copywrite info. udit will write this out
- @s-kennedy will add a box, placement can remain at the bottom

**Comment by uditvira** [comment]
> Just confirming @benhylau does the fetch markdown work across the different protocols (hyper/ipfs)?

Yes this works. looked through the code and also tried on agregore with ipfs. I was asking because I didn't see any checks for protocol immediately, but looking through the code I'm seeing we're using relative links during the fetch

**Comment by benhylau** [comment]
Functionally complete. Closing.

**Comment by uditvira** [comment]
The sentence at the bottom needs to be updated. This should be the same as the language we are currently writing in the foreword
