### ISSUE TITLE
Add benny's piece

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#11]
Wondering if @bennlich can do a pr directly to this repo, instead of someone else putting in the piece for him?

**Comment by bennlich** [comment]
Sounds great!

**Comment by uditvira** [comment]
todos for @bennlich:
- [ ] review your latest feedback
- [ ] integrate code into the repo
- [ ] finish writing the ending
- [ ] write the basket code
- [ ] make it so the back button takes you to the previous snippet
- [ ] show reading progress
- [ ] misc. polish

**Comment by bennlich** [comment]
Reposting the above so I am able to check the boxes

- [x] review your latest feedback
- [ ] integrate code into the repo
- [ ] finish writing the ending
- [ ] write the basket code
- [ ] make it so the back button takes you to the previous snippet
- [ ] show reading progress
- [ ] misc. polish

**Comment by bennlich** [comment]
I think this is done!

**Comment by bennlich** [comment]
Actually a couple of people have missed the begin button. I think I need to fix that and then it's done. Maybe I'll just add an "instructions" section above "thank you".

**Comment by bennlich** [comment]
Okay I think this is done now.

**Comment by uditvira** [comment]
Thank you @bennlich! It's beautiful :)
