### ISSUE TITLE
Pin magazine to Hypercore using beaker browser before launch

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#18]

**Comment by uditvira** [comment]
some troubles getting Beaker to work on apple silicon machines. @YurkoWasHere is setting up a windows vm with Beaker running. Will post hyper key here

**Comment by benhylau** [comment]
>hyper://7c77924ddaa9458e3b54c091121368176bfdb7efc189b42fe66a7a5d29969f44/

This is now pinned on api.distributed.press server.

**Comment by uditvira** [comment]
Great! Closing

**Comment by YurkoWasHere** [comment]
Synced 7:41 AM commit 800e07d30a97d3287cbd339bea326219a423ee12

hyper://7c77924ddaa9458e3b54c091121368176bfdb7efc189b42fe66a7a5d29969f44/

**Comment by YurkoWasHere** [comment]
Synced: 8:59 Commit c93afeaca7559d01869ebca2b32285018a6fd5fe

hyper://7c77924ddaa9458e3b54c091121368176bfdb7efc189b42fe66a7a5d29969f44/

**Comment by YurkoWasHere** [comment]
synced 10:15PM commit a6d7d59cbb3d1683357c46417421de3d318de665

hyper://7c77924ddaa9458e3b54c091121368176bfdb7efc189b42fe66a7a5d29969f44/

**Comment by YurkoWasHere** [comment]
Synced Sept 24 8:40 pm commit a215025e51c964ba0aa943801f8e7c1fd12ed8d5

**Comment by uditvira** [comment]
@YurkoWasHere can you do a sync on 09eb8c3?

**Comment by YurkoWasHere** [comment]
Synced Oct 4 4:52 pm commit 09eb8c379146e1902422e18b99e68081a7114bc1
