### ISSUE TITLE
Incorrect domain name in config.json for Distributed Press

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/two.compost.digital#22]
@ASoTNetworks when you created the project, did Distributed Press let you upload the `config.json` in `~/.distributed-press/data/projects/two.compost.digital` or did you do it manually?

Because https://github.com/hyphacoop/two.compost.digital/blob/master/.distributed-press/config.json#L2 is mismatch of the API key and https://github.com/hyphacoop/api.distributed.press/blob/main/api/index.js#L82 should have prevented you from creating that config file. Did you go around it?

**Comment by ASoTNetworks** [comment]
That's interesting my local version have 
```
{
  "domain": "two.compost.digital"
}
```

This is what I uploaded.

**Comment by ASoTNetworks** [comment]
And it looks like the repo had two.compost.digital set too at the start.
https://github.com/hyphacoop/two.compost.digital/commit/a3b11124af2930ccb6379516d2f2359631a3e36e#diff-c57f832bc2e56d0e338da05764d7e657c3ec0b2cafe9595905a291c1dfbda288

**Comment by benhylau** [comment]
Not sure why but all the history of the file has `one` https://github.com/hyphacoop/two.compost.digital/commits/master/.distributed-press/config.json
