### ISSUE TITLE
Remove /pieces/ from url

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#26]

**Comment by uditvira** [comment]
- this works with all pieces except for celine's piece because it's multipage 
- @s-kennedy will try again but will ping for support if needed

**Comment by s-kennedy** [comment]
@benhylau can I get your help with this? I can't figure out how to get the permalink configuration working for Celine's piece, the multipage one. 

I added `pieces: "/:filename/"` to the config.yaml, as it was before. With this configuration, the link for the index page is still /pieces/celine, and then the link for all the other pages in the section is /:filename, so like /002. But I want the index page to be at /celine and the other pages to be at /celine/002. Any thoughts on how to make this happen? I tried using the `:sections` option but that didn't work, and I tried making each page within Celine's section its' own leaf bundle with an index.md file, but that didn't work either.

**Comment by benhylau** [comment]
Let me give it a try. If I can't get it working will throw this over to @bennlich 😀

**Comment by benhylau** [comment]
See: https://github.com/hyphacoop/two.compost.digital/pull/35

**Comment by uditvira** [comment]
This fix seems to work on Hugo 0.86 (tested) and should work on 0.83+. However, looking at https://github.com/hyphacoop/two.compost.digital/blob/14983737b9904cf9f21d19ad319f02c133f8d4be/.travis.yml#L6 we are using hugo 0.80

Assigning @ASoTNetworks to please upgrade hugo and test via distributed press as well.

**Comment by uditvira** [comment]
I made the change to travis.yml and seems like that works now, so closing
