### ISSUE TITLE
Use true italics for piece text

### ISSUE THREAD

**Issue by celinenguyen** [hyphacoop/two.compost.digital#29]
While developing locally, I noticed that the italics in the content look like this:

![image](https://user-images.githubusercontent.com/1417844/132949060-4a97692e-c024-496b-9dcc-6b7a47ce9aff.png)

This is the case for the pieces in issue 1 as well:

![image](https://user-images.githubusercontent.com/1417844/132949185-36b194de-355c-44d0-a392-f35281233c37.png)

It doesn't look like a true italic—more like the existing roman upright typeface has been slanted. The typeface used, however ([Source Serif Pro](https://fonts.google.com/specimen/Source+Serif+Pro)?) has a really nice italic style where the e's and f's and other glyphs are redrawn in a more cursive style:

![image](https://user-images.githubusercontent.com/1417844/132949092-5779dd00-f8dc-4cf9-9442-9d0601600c6e.png)

I think it would be nicer if this italic was used—this would require loading in an additional 1 (or more) font files and adding an `@font-face` declaration to use those files for the italic weights.

Happy to explore making this change myself after I'm doing with the styling for my piece (see #4).

**Comment by benhylau** [comment]
See #32
