### ISSUE TITLE
Implement metadata reveal feature

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#3]
Margaret and Andi are working on a piece about the history of the blue marble project, that they are both actively involved in. Margaret is also the founder of imagesnippets and wants to reveal the metadata of images in her piece.
- a reference: https://imgsnp.co/1sybw
- the goal is to reveal metadata if a user wants to see it
- we don’t need to link out to the “See the triples." This won't work on the Dweb anyway.

**Comment by uditvira** [comment]
Margaret's piece is here: https://docs.google.com/document/d/1HoDqSnGlq41sm6nQJMoqD_uxGw8DxYAS9opaC_T7koo/edit

**Comment by s-kennedy** [comment]
WIP here: https://github.com/hyphacoop/two.compost.digital/tree/issue_3_image_metadata

**Comment by uditvira** [comment]
@s-kennedy and I are wondering if we should stick with the flip or change to a different animation (e.g., a slide to reveal?)
