### ISSUE TITLE
Implement multipage support

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#4]
In issue 02, we need to support one piece that has multiple pages. Here it is 🔒 https://docs.google.com/document/d/1QvJhMj9byqGOfsSX7Yfd7mYQ5y2jAaGwFo1Ce02wEIg/edit

**Comment by uditvira** [comment]
Tal has already reviewed, Mai is still doing another pass.
Celine will do a final pass.

**Comment by uditvira** [comment]
Celine's web files: https://www.dropbox.com/home/20210722%20Draft

**Comment by uditvira** [comment]
and also here: https://drive.google.com/drive/folders/1fAQtVo84mBnZHd0LCfLbMWCpR8w5KQXm?usp=sharing

**Comment by s-kennedy** [comment]
Some questions/things to consider:
- do we need a "back" button or something so people can go back to the first page of the article?
- do we need a secondary menu so people can see all the pages in the article and navigate between them?
- where should we show the bio of the author, I guess on the first or last page of the article?
- we need to separate the two navigation options at the bottom of the multipage template, there's links to go to the next page in the article and links to go to the next article/home page.

**Comment by uditvira** [comment]
@s-kennedy and I had discussed:
- keep the piece more visually separated from the rest of the issue
- build an internal navigation for the piece. consider building a sidebar
- in some way should "progress" or "where you are in" in the piece

**Comment by celinenguyen** [comment]
Just adding a todo list for myself here—apologies for the length, it's partly to remind myself how I plan on implementing these!

### Content

- [ ] Add preliminary [second draft content](https://docs.google.com/document/d/1mp8tNwXewyBGJkn80jF3ihGNWGrn7eZeyKGcREVCrZw/edit?usp=sharing) (🔒 link restricted to only those explicitly added) as Markdown files
- [ ] When text is finalized (after edits from Mai and Tal), update content as needed
- [ ] Do a pass to check all links from page to page
- [ ] Depending on styling decisions, potentially reformat block-level story elements

### Styling

- [ ] **Use frontmatter `season` information to lightly style pages in accordance with season**. Possible values are `[spring, summer, fall, winter]`. Currently I'm thinking of:
    - [ ] Using small Unicode icons like ☀ and displaying them at the top of the page using CSS `::before` or `::after` pseudoelements.
    - [ ] Varying background color to match the season
 - [ ] **Find a way to display user information** (frontmatter `post-count` and `rank` fields) **where available.** (If they are not intended to be displayed, my current draft has the value `hidden` for both of these fields.) Not sure yet what this should look like, need to experiment!
 - [ ] **Decide on how to display block-level story elements:**
     - [ ] Forum posts, which are contained in `blockquote` elements; lead with a username in a `strong` element; and optionally have a user rank tag contained in a `code` element, immediately following the username, if the user is a moderator
     - [ ] Forum PMs, which are contained in `blockquote` elements and have 2 paragraphs
     - [ ] May need to alter how these are formatted in Markdown in order to style them more easily
     - [ ] Might be able to draw from existing styling of `code` blocks (see [this piece from issue 1](https://one.compost.digital/the-ocean-swallowed-a-cable/) for an example)
- [ ] **Style links to next story page(s)**
   - [ ] May want to remove the → character from the Markdown and instead insert it via CSS? Not sure
 - [ ] **Consider whether usernames within paragraphs should be styled differently**

**Comment by uditvira** [comment]
@s-kennedy will merge current pagination changes into celine's working branch
also a nice to have is: the number of dots on a time segment accurately reflect the number of choices available in that time segment. right now we have a fixed number of dots (2) for all the time segments that have choices.

**Comment by uditvira** [comment]
Sharon has implemented this:
> the number of dots on a time segment accurately reflect the number of choices available in that time segment. right now we have a fixed number of dots (2) for all the time segments that have choices.

we're just waiting for Celine to update her branch with styles and content

**Comment by celinenguyen** [comment]
Hello all—really sorry for the delay on this! Have fallen behind while working on edits to the piece text, but will push some styling changes this Friday and Saturday (10–11 Sep).

**Comment by uditvira** [comment]
No worries Celine! Looking forward to seeing your finished piece!

**Comment by celinenguyen** [comment]
Updated my branch (PR forthcoming) with the text as it stands + a lot of styling. Some screenshots below!

Link styling (bottom is the hover state)

<img width="783" alt="Screenshot 2021-09-11 at 11 04 26 pm" src="https://user-images.githubusercontent.com/1417844/132962750-3268fdff-51e6-48d3-92ec-0f1da11b6e33.png">

Private message styling:

<img width="661" alt="Screenshot 2021-09-11 at 11 04 45 pm" src="https://user-images.githubusercontent.com/1417844/132962757-93388107-a82e-41e3-8f2e-73dde22a2053.png">

Post styling:

<img width="673" alt="Screenshot 2021-09-11 at 11 02 30 pm" src="https://user-images.githubusercontent.com/1417844/132962766-1a51bba7-5691-4a92-b53d-f51523a02b89.png">

Frontmatter for season, post count, rank. Colors vary by season; the images below are ordered spring, summer, fall, winter.

<img width="762" alt="Screenshot 2021-09-11 at 11 15 27 pm" src="https://user-images.githubusercontent.com/1417844/132963181-cc21e7c6-eb9e-45d8-821d-f6a3b1d7ce57.png">

<img width="772" alt="Screenshot 2021-09-11 at 11 17 15 pm" src="https://user-images.githubusercontent.com/1417844/132963187-2bccc5e8-eaeb-479d-9a50-15462e11859d.png">

<img width="768" alt="Screenshot 2021-09-11 at 11 19 29 pm" src="https://user-images.githubusercontent.com/1417844/132963189-b416b0fa-6066-4933-8f9c-b71752a49ae7.png">

<img width="770" alt="Screenshot 2021-09-11 at 11 20 58 pm" src="https://user-images.githubusercontent.com/1417844/132963191-0cf5f138-378a-48e5-b273-ebc051395d0a.png">

**Comment by celinenguyen** [comment]
Put up a PR (https://github.com/hyphacoop/two.compost.digital/pull/30) for the content and styling. I'm now realizing it would have been easier to review if I'd separated out content import and styling, but there was a bit of back-and-forth (changing Markdown formatting to make it easier to select different elements).

**Comment by uditvira** [comment]
PR #30 has been merged. Closing this issue
