### ISSUE TITLE
Cover design finalization 

### ISSUE THREAD

**Issue by wakest** [hyphacoop/two.compost.digital#41]
I mentioned some issues in the matrix about the new cover design and thought maybe starting an issue here would be good. Would like to figure out how everyone can be happy with the cover.

**Comment by uditvira** [comment]
documenting the concerns that @wakest raised:
- the layered bottom part doesn't match wakest's intention of having separated out scanned pieces
- the weighting of the title
- "issue 02" without a background

possible paths forward:
- a bottom footer was made that could possibly be reused here

@wakest are you interested in working on this issue? I'd like to talk about how to move this forward

**Comment by wakest** [comment]
What can I do to help?

**Comment by wakest** [comment]
here is my first attempt at redoing it to have some of the aspects of the redesigned cover while also retaining more of my aesthetic (currently the text is blurry, and would fix that first)
![draftcover](https://user-images.githubusercontent.com/7890201/133892594-b29eae3a-0f93-4137-925c-27ff813e0712.gif)

**Comment by uditvira** [comment]
Hey @wakest, thank you for sending this new iteration! Mai and I discussed and have some feedback:

**1. Look and feel consistency from the last issue** 

Although each issue can have certain distinct elements, together, covers from all issues should feel like a cohesive whole. If you look at this cover vs. the last issue cover, this one feels overly symmetrical and with less elements that make it pop. 

We understand you don't want to layer your scans, but can you add more of your images -- perhaps in a haphazard pattern -- much like what we have with the leaves in the footer? COMPOST is more organic/messy vibes and not clean/modern. So what you've shared might look nice as a standalone cover, but think it doesn't fully match COMPOST's feel.

**2. Higher contrast**

It needs more black/darker colours to balance against the header of the website. The current verson is too washed out and doesn't draw the eye in.

The leaf behind the title in the last version was one way of sorting out both of these issues. We were pretty happy with the leaf and would encourage you to explore in that direction. We're sharing the transparent layer Hanami made that has the title over the black leaf. 

What do you think about incorporating this feedback in a new version?

![Compost_issue02_v1](https://user-images.githubusercontent.com/9661586/133898003-54efe32c-fad1-4f3a-91ef-f90d27a27ffc.png)

**Comment by wakest** [comment]
an attempt at playing with the constraints that you want it to pop out more. I really don't like the bubble drawn letters over the leaf. Mentioning the symmetry, the version I originally made was intentionally non symmetrical with the leaf holding the text entirely within it on the upper right corner. 
![original_bfdcd66f7cbf545e3c592990da8ced77(1)(1)](https://user-images.githubusercontent.com/7890201/133906972-0affc60d-02ff-4757-969b-2ed8dc5ec9fc.gif)

heres a different direction that has less symmetry
![original_bfdcd66f7cbf545e3c592990da8ced77(1)(1)(1)](https://user-images.githubusercontent.com/7890201/133907738-185c2517-7c1e-4731-a2a3-7811b7860496.gif)

**Comment by maisutton** [comment]
Hey Liaizon, I really appreciate you taking our feedback and trying these new directions--but I'm really sorry to say that none of these covers are working for me.

Here are some of the elements that I don't like:
    * The shadow effect on Inoculate
    * The snow globe effect under the title
    * The overall balance of the design

We really want to respect your time, while also seeing if we can come up with some new versions we all like.

I'm gonna see if Hanami can try a few other directions with it to see if we can achieve the stylistic cohesion with the issue 01 cover, without using your scans in a way that make you uncomfortable. 

We'll share those here as soon as we have them!

**Comment by maisutton** [comment]
Hi there, Hanami and I worked on this new version. We tried a simplified design with this halftone pattern--thought it evoked spores/spreading/inoculation. 

![Issue02_Cover_Halftone](https://user-images.githubusercontent.com/21212603/133916472-75da22b7-1ac7-41dd-93c9-63b43552d2fa.png)
?

**Comment by benhylau** [comment]
The hard boundaries from @wakest's designs don't work for me. I actually felt that could be a problem too when you guys planned to take the footer as the bottom. Because the bg is dynamic and patterned, sticking a solid dividing line on there, transparent of not, would not look nice.

I like the last one from Hanami made bc the boundaries are softer, and all elements exists in better harmony.

**Comment by wakest** [comment]
Great, glad you found something that works for y’all.

**Comment by uditvira** [comment]
Ok seems like this covers wakest's original concerns

> the layered bottom part doesn't match wakest's intention of having separated out scanned pieces
> the weighting of the title
> "issue 02" without a background

I swapped it out on the main branch. Closing this issue for now. Please re-open a new issue if there are pending concerns
