### ISSUE TITLE
Content fixes and polish

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#45]
- [x] Foreword:
  - [x] change the smiley face at the end to (´• ω •`)ﾉ
  - [x] @maisutton adding some thankyous and shoutouts
- [x] Eeshita:
  - [x] footnotes don't seem to work
  - [x] link to killjoynetwork doesn't work. Might be missing ssl certs
  - [x] fix italics in a couple places (search for '_')
  - [x] remove first anigif
  - [x] move the green anigif before dear reader
  - [x] move the grayscale anigif down before the map
 - [x] Luandro:
   - [x] the images aren't using the figure shortcode 
 - [x] Sultana:
   - [x] italics in a few places aren't rendering
   - [x] move all the links to footnotes
   - [x] switch TK to Udit
   - [x] change first anigif to bamboo stick
   - [x] add banner image before tal's question about fieldness
   - [x] move map image higher in the piece, right before the "by way of an engineering background"
   - [x] put both moth images back to back
- [x] Celine:
  - [x] add bio
  - [x] follow up about cover image and teaser @maisutton 
 - [x] Kola
 - [x] Benny
   - we had a question about making more obvious that you need to click "begin", but we think it's good for now because most people seem to get it and we can get feedback as we go along
 - [ ] Margaret and Andi
   - [ ] email them to confirm that their metadata looks good
   - [x] promote header for "Around the World with the Blue Marbles"
   - [x] use the figure shortcode for their images
   - [x] clay marbles typo "a a type"
   - [x] remove "GIF: Wakulla Springs, Florida" at the end
- [x] Liaizon
  - [x] missing teaser "Ritualistic curation of nature into the digital realm."
  - [x] this sentence should be italicized "All .gifs lovingly collected from the Kickapoo region of Wisconsin in July of 2021, in and around the childhood home of Liaizon Wakest."

**Comment by maisutton** [comment]
Made edits to Liaizon's piece and followed up with Celine re: teaser and cover image.
