### ISSUE TITLE
Flow first round of copy into magazine

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#6]
Get first drafts from editorial and flow into issue two repo content folder

- [x] Foreword in the flow-content branch
  - @benhylau, @uditvira  to do a close read
- [x] Ten Years Later: There Are 12 Users Online
  - see #30 
- [x] Re:Sister - The Killjoy Cooking Network
  - see #5 
- [x] IndiNet: Autonomous Indigenous Network in the flow-content branch
- ~[ ] Compost This: Composting the Past In the Future-Present~
- [x] Qubit Guarantee in the flow-content branch
- [x] clock basket no. 1 (working title)
  - see #11 
- [x] The Blue Marble Smiles Project in the flow-content branch
- [x] Growth Through Replication
- [x] Interview in the flow-content branch

**Comment by uditvira** [comment]
We'll get these drafts in August 20th

**Comment by zeroexp** [comment]
Andi and I are going to change the name of our piece. We are working on it now.

**Comment by wakest** [comment]
@uditvira just got the ok on the final draft from Mai on Thursday and just added all the edited text back into https://multiverse.plus/wakest/gif-praxis-2nd-draft (I over wrote the 2nd draft so this is really the 4th and final version of the text with the old link. need to extract the HTML now)

**Comment by wakest** [comment]
need to extract this in a different way and totally optimize the assets but putting this here anyway [gif-praxis.svg.zip](https://github.com/hyphacoop/two.compost.digital/files/7112386/gif-praxis.svg.zip)
multiverse exports as an .svg file with all the gifs included (which I didn't even know you could do)

**Comment by uditvira** [comment]
this is happening in the flow-content branch

**Comment by uditvira** [comment]
closing this because we've moved the first round of copy in. upcoming polish and content edits to follow in #45
