### ISSUE TITLE
Travis free credit used up for org

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/two.compost.digital#69]
CI is disabled now: https://app.travis-ci.com/organizations/hyphacoop/plan/usage

**Comment by ASoTNetworks** [comment]
Currently we are on the free plan which includes 10000 credits that are all used up.

Travis CI charges $69 USD/month or $759USD/year for 1 concurrent job.

**Comment by benhylau** [comment]
Moving to GH actions

**Comment by ASoTNetworks** [comment]
Opened PR https://github.com/hyphacoop/two.compost.digital/pull/70
