### ISSUE TITLE
Finalize which versions of look and feel assets we're using

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#7]
@wakest has been working on some amazing gifs for this issue. Creating this issue to track final versions of assets we're using.

~- [ ] cover image~ see issue #41 
- [x] section separators for pieces
- [x] background pattern
- [x] footer image

**Comment by uditvira** [comment]
- for the background, we'll be using this one: https://github.com/hyphacoop/two.compost.digital/blob/master/static/images/background/background-dithered.jpg 
- the dividers are in place here: https://github.com/hyphacoop/two.compost.digital/tree/master/static/images/dividers

**Comment by uditvira** [comment]
There were shortcodes for the dividers in the last issue, @s-kennedy can you make sure they work for issue 02?

**Comment by s-kennedy** [comment]
WIP here: https://github.com/hyphacoop/two.compost.digital/tree/issue_7_look_and_feel

**Comment by uditvira** [comment]
s-kennedy and I discussed:
- take some more images from https://www.are.na/liaizon-wakest/graphic-compost 
- ask @wakest if the divider images can be transparent and if we can get more from the arena channel in the right size for making into dividers
- we both think the dithered and gray scale photographic elements are working better than the filled in/opaque/solid black ones as dividers

**Comment by uditvira** [comment]
also looks like all the css/layout from issue one haven't been cloned into issue 02. @s-kennedy will take a look at this!

**Comment by uditvira** [comment]
@s-kennedy will extract colours from this https://www.are.na/block/12411112 and start adding to a few places to get a cohesive look and feel:
- links
- code background

**Comment by uditvira** [comment]
Hey @s-kennedy, @wakest has been sharing their work in the Matrix chat, perhaps you may want to check out the convo there? They're still iterating on the colours

**Comment by uditvira** [comment]
@s-kennedy has all the setup done, we're just done waiting for @wakest to clean these up and commit them to the repo based on our last convo:
* https://www.are.na/block/12510545 split up into 3
* https://www.are.na/block/12510738
* https://www.are.na/block/12586845
* https://www.are.na/block/12510651
* https://www.are.na/block/12556407
* https://www.are.na/block/12510652

**Comment by uditvira** [comment]
a few more asks for @wakest 
- can you share the collage of leaves that you're working on the for the footer. @s-kennedy will work with that 
- also would it be possible to recolour this image https://github.com/hyphacoop/two.compost.digital/blob/master/static/images/background/background-cropped-fullcolor.jpg to bring it closer to the cover image colors. if you aren't able to do that, is it okay for @s-kennedy to experiment with some colours for that image?

**Comment by uditvira** [comment]
Also Hanami will be doing another iteration on the cover, building on the great work that wakest has already done!

**Comment by wakest** [comment]
hey sorry things did not go as expected in Denmark, my internet just barely worked on this computer while I was here I don't know why. @uditvira here is the PSD of the footer I had sent that screenshot of (made in Gimp so hope it loads) its just frames separated from two leaf gifs so easy to replicate if the PSD wont open.  This image is the dimensions from the issue two footer.
[footer.psd.zip](https://github.com/hyphacoop/two.compost.digital/files/7112308/footer.psd.zip)

**Comment by wakest** [comment]
I just did figured out how to recolor template image in gimp and was uploading it but now see someone already got it up on two.compost.digital

**Comment by s-kennedy** [comment]
> I just recolored the background-cropped-fullcolor.jpg in gimp and was uploading it but now see someone already got it up on two.compost.digital so alas

@wakest that was me, I just made a temporary version to see how the page looked overall, but I don't think I got the colours quite right so I'm happy to sub in yours if you can get it uploaded!

**Comment by wakest** [comment]
@s-kennedy the one I did honestly looks exactly like yours I cant really tell the difference so I don't think there is any reason to change it (:

**Comment by wakest** [comment]
I made a new small sized animated divider stick and checked how it looked on a page and I think it works pretty well, def more happy with it then the bamboo one currently being used: https://two.compost.digital/images/dividers/72pixelstick.gif

**Comment by wakest** [comment]
reference screenshot ![image](https://user-images.githubusercontent.com/7890201/132504070-38ddafc9-d982-49b3-baff-411278b475db.png)

**Comment by wakest** [comment]
@s-kennedy wow the footer looks great! did you do that? also I saw you added the new version of the stick separator already into the pages! thank you sorry it took so long to get it up.

I added some more separators that are dithered smaller that can be sprinkled through the site 

here is a 72px high version of the leaf gif in color and black and white (and transparent)
https://github.com/hyphacoop/two.compost.digital/blob/master/static/images/dividers/72-colornettles.gif
https://github.com/hyphacoop/two.compost.digital/blob/master/static/images/dividers/72-bw-nettles.gif

(this one is made from current berry stems also constrained to 72px high)
https://github.com/hyphacoop/two.compost.digital/blob/master/static/images/dividers/72-currentstem.gif

**Comment by s-kennedy** [comment]
@wakest yes I made the footer based on the PSD file you shared, I'm glad you like it! I've added the rest of the gifs you just added to the list so we can now use them with the shortcode. 

@uditvira @maisutton when you are flowing in the content, you can find the list of names of the gif dividers here: https://github.com/hyphacoop/two.compost.digital/blob/master/data/gifs.yaml

...and you would use it like this: `{{< anigif name="berries_on_stem" >}}`

Also @wakest I tried to replicate the layout of your piece from the metaverse page, this is what it looks like: https://two.compost.digital/pieces/growth-through-replication. Does that look okay to you? Any feedback?

**Comment by wakest** [comment]
@s-kennedy I saw thank you so much! most of it looks quite good! the main thing that sticks out is the placement of the scans. 

this is how its showing up for me on firefox (non high dpi screen)
![image](https://user-images.githubusercontent.com/7890201/132585672-2e1ef4ff-787b-4cea-90f9-02e3fe244250.png)

and this is what it looks like on the original 
![image](https://user-images.githubusercontent.com/7890201/132585793-7f159768-08ad-4e6c-8ed5-8c437b6d10e6.png)

**Comment by s-kennedy** [comment]
@wakest oh yeah you're right, the image was too small. I made it bigger now (50%) but I left the text beside it instead of overlapping, because with the larger text we're using the text was overlapping on the leaves and it was hard to read, especially on a tablet-sized screen. On mobile I have the image coming before the text. Does that look ok?

**Comment by uditvira** [comment]
I updated the cover image but it's quite large ~11.6 mb. This is causing the load time to be quite long. Two options are:
- export a lower size gif and use this, but not sure if this possible
- replace with a static image that preloads before the gif

**Comment by maisutton** [comment]
If we can make the second option work we should do that!

**Comment by uditvira** [comment]
@s-kennedy can you implement option 2, with the attached img?

![Compost_issue02_v2a](https://user-images.githubusercontent.com/9661586/133662587-a5fee98b-60d3-409c-9013-c2365c11c6af.jpg)
h
