### ISSUE TITLE
Links break on gateways

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/two.compost.digital#72]
- [x] The checkmark button on copying text breaks on IPFS gateway
    <img width="425" alt="Screen Shot 2021-09-20 at 3 33 34 PM" src="https://user-images.githubusercontent.com/2261308/134085676-8f258ef9-9479-49bb-9eb2-b3d210d429d9.png">
- [x] Copy markdown text fetch gets 404 on IPFS gateway
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
- [x] The map in https://ipfs.distributed.press/ipns/two.compost.digital/re-sister/ is broken, something broke relative links in the port from Micah's version to the now `annotated-map.js` it seems
    ![Screen Shot 2021-09-20 at 4 52 19 PM](https://user-images.githubusercontent.com/2261308/134091814-4f0ae364-1f6b-46e4-a09e-6e2847c92f16.png)

**Comment by benhylau** [comment]
@s-kennedy  Is `data/piece-sequence.yaml` used to determine page order?

`layouts/partials/prev-and-next-buttons.html` seems to work even when the data there was wrong?

**Comment by uditvira** [comment]
> @s-kennedy  Is `data/piece-sequence.yaml` used to determine page order?
> 
> 
> 
> `layouts/partials/prev-and-next-buttons.html` seems to work even when the data there was wrong?

No the weights determine sequence. See README.md

**Comment by benhylau** [comment]
Yes, then what is `piece-sequence.yaml` doing there, and why is the html using it?

**Comment by YurkoWasHere** [comment]
RE: `copy markdown text fetch gets 404 on IPFS gateway`
Looks like the markdown is `../../filename.md` and should be just `../filename.md`

in html the extra ../ is ignored. but in IPFS it loosed the IPNS path

see markdown path at http://two.compost.digital/content/pieces/re-sister/index.md

additionally

`onclick="fetchMarkdown(&#34;/../../markdown/re-sister.md&#34;)"`

looks like the first `/` makes the path absolute note relative

**Comment by benhylau** [comment]
I think #73 #74 fixes all of these.

## Some notes on IPFS gateway testing

To debug this, I serve this on my local machine both on a standard webserver and via a HTTP gateway.

First I need to set up the local IPFS gateway, by installing IPFS Desktop then add custom configurations to change my gateway to a subpath one: 

```
		"PublicGateways": {
			"localhost": {
				"NoDNSLink": false,
				"Paths": [
					"/ipfs",
					"/ipns"
				],
				"UseSubdomains": false
			}
		},
```

Then I test with:

- HTTP webserver: http://localhost:1313/re-sister/
- HTTP IPFS gateway: http://localhost:8080/ipfs/QmSaFFKa7ttvNtvPxXsdNCSN1fyHepsRGEnWDVYxx8cMqS/re-sister/
