### ISSUE TITLE
Update data/people.yml with name + bios

### ISSUE THREAD

**Issue by uditvira** [hyphacoop/two.compost.digital#8]
We need these from contributors

**Comment by uditvira** [comment]
This will be updated here: https://pad.riseup.net/p/wNHgFLdLr7yIcEdA3jfw-keep

**Comment by benhylau** [comment]
@uditvira do we want to move `Find out more about them on https://wake.st` to Back Cover where all other links are? I think we aren't putting links on pieces.

We don't have one for Interview right?

We are just waiting on Celine's otherwise.

**Comment by uditvira** [comment]
this is done
