### ISSUE TITLE
URLs got changed with an added "piecelast" section in the URL

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/two.compost.digital#95]
There was an article published under: https://two.compost.digital/clock-basket-no-1/

It is now published under https://two.compost.digital/pieceslast/clock-basket-no-1/

This is likely due to #94 or something to do with hugo.

I have no clue how the build works so help would be appreciated in figuring that out.

**Comment by bennlich** [comment]
@RangerMauve I saw in the PR you linked that the version of hugo used in the build was changed from latest to 0.80.0 here: https://github.com/hyphacoop/two.compost.digital/pull/94/files#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R26

This appears to be the bug. I tested the latest version of hugo locally and had no issues with the URLs. Then I tested version 0.80.0 locally and saw the same weird URLs that are currently online. So I think the fix would be to revert to using a newer version of hugo in the build script.

**Comment by benhylau** [comment]
Thanks for investigating this @bennlich I upgraded to `0.89.4` (latest) in https://github.com/hyphacoop/two.compost.digital/pull/96 and it did indeed fix the URLs. Pls confirm this matches the old link: https://two.compost.digital/clock-basket-no-1/

Strangely, https://one.compost.digital does not suffer from this problem even though it uses `0.80.0`. I have created a PR there too https://github.com/hyphacoop/one.compost.digital/pull/32 (tagged @RangerMauve @ASoTNetworks) and we should probably upgrade for consistency.

**Comment by bennlich** [comment]
Yay! Thanks @benhylau ! Yep, that's the correct URL.
